spring.application.name=csv-processor

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/zipdb
spring.datasource.username=postgres
spring.datasource.password=sardukar@101#


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


cache.zipcode.maximum-size:10000

logging.level.com.example.learn:DEBUG
logging.level.org.hibernate.SQL:WARN
logging.file.name:logs/csv-processor.log

csv.executor.consumers:20
csv.executor.producers:3
csv.executor.jobPool:1